baseURL = "https://www.notifuturo.com/"
languageCode = "es-es"
title = "NotiFuturo"
theme = "PaperMod"

[params]
  # Display options
  showReadingTime = true
  showPostNavLinks = true
  showShareButtons = true
  showCodeCopyButtons = true
  showWordCount = true
  comments = false
  
  # Theme-specific settings
  defaultTheme = "auto"  # auto/light/dark
  disableSpecial1stPost = false
  disableScrollToTop = false

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archivo"
    url = "/posts/"
    weight = 2

[services]
  [services.googleAnalytics]
    ID = ""  # Add your GA ID if needed

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
